/**
 * @description       : 
 * @testing           : 
 * @author            : FSM
 * @last modified on  : 06-23-2025 - FSM
 * @last modified by  : FSM
**/
public class SmartAdvCaseDto {
    public String firstName {get;set;}
    public String lastName {get;set;}
    public String phone {get;set;}
    public String email {get;set;}
    public String summary {get;set;}
    public String searchEngineName {get;set;}
    public String address {get;set;}
    public String city {get;set;}
    public String state {get;set;}
    public String zip {get;set;}
    public String referringURL {get;set;}
    public String keywords {get;set;}
    public String intakeDate {get;set;}
    public String dob {get;set;}
    public String gender {get;set;}
    public String ssn {get;set;}
    public String caseType {get;set;}
    public String office {get;set;}
    public Boolean ssnEncoded {get;set;}
    public String sfIncidentDetailId {get;set;}
    public String sfContactId {get;set;}
}